In [13]:
import numpy as np

def naive_add(x,y):
    assert(len(x.shape) == 2)
    assert(x.shape == y.shape)
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = y[i,j]
    return x

def naive_relu(x):
    assert(len(x.shape) == 2)
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j], 0)
    return x

import time
x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
z = naive_add(x,y)
z = naive_relu(z)
print(f"Took: {(time.time() - t0):.4f} s")
t0 = time.time()
z = np.maximum(x + y, 0)
print(f"Took: {(time.time() - t0):.4f} s")


Took: 0.0019 s
Took: 0.0002 s


In [14]:
x = np.random.random((32,10))
y = np.random.random((10,))

In [15]:
y = np.expand_dims(y, axis=0)

In [17]:
Y = np.concatenate([y] * 32, axis=0)

In [18]:
Y.shape

(32, 10)

In [20]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y,x)
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [21]:
x = tf.Variable(tf.random.uniform((2,2)))
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y,x)
grad_of_y_wrt_x  

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [39]:
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2,2))
print(W)
print(x)
print(b)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad = tape.gradient(y, [W, b])
grad

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.01729894, 0.35299265],
       [0.5292913 , 0.63248813]], dtype=float32)>
tf.Tensor(
[[0.7249223  0.05842233]
 [0.08925986 0.6952554 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.81418216, 0.81418216],
        [0.7536777 , 0.7536777 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]